package com.technostore.test.utils

object TestData {
    const val DEFAULT_PASSWORD = "123456"

    const val VLAD_ACCESS_TOKEN =
        "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJiZjc0YTBiMjkyOGI0YjA0ODAwODc4YTZjNmYwYTI1YyIsInN1YiI6InZsYWQxMjNAeWFuZGV4LnJ1IiwiaWF0IjoxNzEwMDE2MDEzLCJleHAiOjE3NDE1NTIwMTJ9.PBJQbK_5Zi3EKwSCp0Zt15WxdMEVG7Z0fBTSH6KLHi-E1ir7NHjmE_GyAimNQQUBpKYG4no-mrMq4NF8lbhA1Q"
    const val VLAD_REFRESH_TOKEN =
        "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxYzQzNmY0NjVmNTM0MWM5YjIzYjI4ZDI5MzQzZGRmZSIsInN1YiI6InZsYWQxMjNAeWFuZGV4LnJ1IiwiaWF0IjoxNzEwMDE2MDQwLCJleHAiOjE3NDE1NTIwNDB9.7zNV7_i7tjID_NuTCT0uMNLhVWcB56VYKunwQzggrknGKcAQinEmA2r8Y_RzTGojh9Q4gEZc-YJOGp_oA9LhDg"
    const val VLAD_EMAIL = "vlad123@yandex.ru"
    const val VLAD_NEW_PASSWORD = "1234567"

    const val DANIL_EMAIl = "danil@yandex.ru"

    const val IVANOVA_EMAIl = "ivanova.a@yandex.ru"
    const val IVANOVA_NAME = "Анастасия"
    const val IVANOVA_LAST_NAME = "Иванова"
    const val IVANOVA_NEW_NAME = "Игорь"
    const val IVANOVA_NEW_LAST_NAME = "Иванов"
    const val IVANOVA_ACCESS_TOKEN =
        "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiI0NWQwN2E2YzYzZmU0Y2EwYjgxZmU1NzhkNTQ1ZWJkYiIsInN1YiI6Iml2YW5vdmEuYUB5YW5kZXgucnUiLCJpYXQiOjE3MTAwMTg1MDgsImV4cCI6MTc0MTU1NDUwOH0.jevXRK5k0sFz1Dcalj_tigqsusLvMkmII4JpG9_zLEPdZZZYPECBtdTHBoXWdIqcIk_ASWGEynl_I9chuDA5WA"
    const val IVANOVA_REFRESH_TOKEN =
        "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJjZDc0MThiNjRkMjU0NWU4YWI2ZjZhYWFjMjQ5NTEyNCIsInN1YiI6Iml2YW5vdmEuYUB5YW5kZXgucnUiLCJpYXQiOjE3MTAwMTg1MjYsImV4cCI6MTc0MTU1NDUyNn0.XN6IuZ9pbhJz6tCvNxUqxl1FlKQw4DK6ByBEFY6Aeh95Yj6qvwC8lDhXHnxfH6Czx3BzZRrowCER3hhDBZqyyQ"

    const val ALENA_ACCESS_TOKEN =
        "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiI2ZGY3OTVhMjhmMzE0Y2YzYTMwOGRmMTNiNDM2ZDRhNCIsInN1YiI6Iml2YW5vdmEuYTJAeWFuZGV4LnJ1IiwiaWF0IjoxNzEwMDU0MjUyLCJleHAiOjE3NDE1OTAyNTJ9.P92FElhXOJascwQJJzmzRLW7RQUKI6s6reCkcmlrgg6hhAw63MGRsxiuBZTdC4M0WA6GBQVCW0lDRyMQD-mmtQ"
    const val ALENA_REFRESH_TOKEN =
        "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiI1Y2FiYmIxYTVjOGM0YmEyOWFkYTY0ZTlmMTFkZjlkMSIsInN1YiI6Iml2YW5vdmEuYTJAeWFuZGV4LnJ1IiwiaWF0IjoxNzEwMDU0MjY4LCJleHAiOjE3NDE1OTAyNjh9.8h8_scmwNv1tc567Gr9ntFEmH04eaI-HjhtYKIUp5pYLj_7l1N7wSD6vsF9Q1TZGSqT4cp65EmDkrJsPZCVx5Q"
    const val ALENA_EMAIL = "ivanova.a2@yandex.ru"

    const val PETROV_ACCESS_TOKEN =
        "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxNTk4NTg3YmZlNTc0YzE2OTQ2Y2E1NDI1YjJiZDZlYiIsInN1YiI6ImEucGV0cm92QHlhbmRleC5ydSIsImlhdCI6MTcxMDA1NDkwMywiZXhwIjoxNzQxNTkwOTAzfQ.CFsSVgFYvW8fbsyoQuRl8LDcmk9OTKFjAozbDepRCMTPtf_v9KAGHmtnnwwIzOVx6QUb6cBjD7-hhbskMTD_Hw"
    const val PETROV_REFRESH_TOKEN =
        "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzNTE0OGFlZmVhZDQ0NWY3OTBkZjA5Mzk3MTU5NDUyNyIsInN1YiI6ImEucGV0cm92QHlhbmRleC5ydSIsImlhdCI6MTcxMDA1NDkyNCwiZXhwIjoxNzQxNTkwOTI0fQ.a6iiTEXtmG3EAZxh863bANXrnTbIBvgarQFxN9hzwmIV1lkN_K2Yp4yZnoV4vJgcFAmFDp30Ao2R7KPg8CLEjg"
    const val PETROV_EMAIL = "a.petrov@yandex.ru"
}