server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8080/eureka/}

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/user-service/**
        - id: product-service
          uri: http://localhost:8085/
          predicates:
            - Path=/products-service/**
        - id: review-service
          uri: http://localhost:8083/
          predicates:
            - Path=/review-service/**
        - id: order-service
          uri: http://localhost:8086/
          predicates:
            - Path=/order-service/**