spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/orders
    driverClassName: com.mysql.cj.jdbc.Driver
    password: somepassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8080/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: order-instance
    preferIpAddress: true
server:
  port: 8086
