name: client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  client_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Build with Gradle
      run: |-
        cd client
        ./gradlew :app:assembleDebug
  
  client_unit_tests:
    needs: client_build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Run unit tests
      run: |-
        cd client
        ./gradlew :app:assembleDebugAndroidTest testDebugUnitTest
