name: client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  client_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Build with Gradle
      run: |-
        cd client
        ./gradlew :app:assembleDebug
  
  client_unit_tests:
    needs: client_build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Run unit tests
      run: |-
        cd client
        ./gradlew :app:assembleDebugAndroidTest testDebugUnitTest
   
    - name: Run Module Coverage
      run: |-
        cd client
        ./gradlew allDebugCoverage

    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: |
          ${{ github.workspace }}/**/build/reports/jacoco/allDebugCoverage/html/index.html,
        token: ${{ secrets.TOKEN }}
        title: Code Coverage
        debug-mode: false

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
