name: Run UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    # - name: Set up Android SDK
    #     uses: actions/setup-android@v2
    #     with:
    #       sdk-version: '29'
    
    - name: Build app
      run: |-
        cd client
        ./gradlew assembleDebug
    - name: Run tests
      uses: emulator-wtf/run-tests@v0
      with:
        api-token: AgAAKcAuxmGrquNZY8YnC6fDQKEnEEnjrdOiSMDw/haUcwhPwBEjitITZNEk9b3ibFXMWtIcTvlSD5zj/2Y2Ug87UJCaRZaq4ttdi/iA0q0KkoAd3kwIVpUiv3EF/Z69uYx+C1J3Waip+a9aFXo8V7UpFt97L40tPYcS+Ud6L8iL0KIrMmu3oN7a5g9z9RI5R78N
        app: client/app/build/outputs/apk/debug/app-debug.apk
        test: client/app/build/outputs/apk/debug/app-debug.apk
        outputs-dir: build/test-results
        devices: |
          model=Pixel2,version=29
    
    - name: Publish test report
      uses: mikepenz/action-junit-report@v2
      if: always() # always run even if the tests fail
      with:
        report_paths: 'build/test-results/**/*.xml'