name: run UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mysql-orders:
    runs-on: ubuntu-latest
    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'orders' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'strongpassword' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'mysql' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'strongpassword' # Required if "mysql user" exists. The password for the "mysql user"
    - name: Create Table
      run: |
        sudo service mysql status
        
  mysql-review:
    runs-on: ubuntu-latest
    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'review' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'strongpassword' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'mysql' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'strongpassword' # Required if "mysql user" exists. The password for the "mysql user"

  # run-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: set up JDK 17
  #     uses: actions/setup-java@v3
  #     with:
  #       java-version: '17'
  #       distribution: 'zulu'
  #       cache: gradle
    
  #   - name: Setup Gradle
  #     uses: gradle/gradle-build-action@v3
    
  #   - name: Build app
  #     run: |-
  #       cd client
  #       ./gradlew assembleDebug  app:assembleDebugAndroidTest
  #   - name: Run tests
  #     uses: emulator-wtf/run-tests@v0
  #     with:
  #       api-token: ${{ secrets.EW_API_TOKEN }}
  #       app: client/app/build/outputs/apk/debug/app-debug.apk
  #       test: client/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  #       outputs-dir: build/test-results
  #       devices: |
  #         model=Pixel2,version=29
  #       record-video: true
  #   - name: Publish test report
  #     uses: mikepenz/action-junit-report@v2
  #     if: always()
  #     with:
  #       report_paths: 'build/test-results/**/*.xml'