name: run UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mysql:
    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v1

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done       
  # run-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: set up JDK 17
  #     uses: actions/setup-java@v3
  #     with:
  #       java-version: '17'
  #       distribution: 'zulu'
  #       cache: gradle
    
  #   - name: Setup Gradle
  #     uses: gradle/gradle-build-action@v3
    
  #   - name: Build app
  #     run: |-
  #       cd client
  #       ./gradlew assembleDebug  app:assembleDebugAndroidTest
  #   - name: Run tests
  #     uses: emulator-wtf/run-tests@v0
  #     with:
  #       api-token: ${{ secrets.EW_API_TOKEN }}
  #       app: client/app/build/outputs/apk/debug/app-debug.apk
  #       test: client/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  #       outputs-dir: build/test-results
  #       devices: |
  #         model=Pixel2,version=29
  #       record-video: true
  #   - name: Publish test report
  #     uses: mikepenz/action-junit-report@v2
  #     if: always()
  #     with:
  #       report_paths: 'build/test-results/**/*.xml'