name: "review-service"

on:
  push:
    paths:
      - "api/review-service/**"
      - ".github/workflows/review-service.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |-
          cd api/review-service
          mvn -B -DargLine="-ACTIVE_PROFILE=default -CONFIG_URI=http://localhost:8088" package --file pom.xml -DskipTests
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      ACTIVE_PROFILE: default
      CONFIG_URI: http://localhost:8088
      SPRING_PROFILES_ACTIVE: native
      EUREKA_HOSTNAME: localhost
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run serverconfig
        env:
          SERVER_PORT: 8088
        run: |-
          cd api/serverconfig
          mvn spring-boot:run &
      - name: Run eurekaserver
        run: |-
          cd api/eurekaserver
          mvn spring-boot:run &
      - name: Run gateway-server
        run: |-
          cd api/gateway-server
          mvn spring-boot:run &
      - name: Run tests for review-service
        run: |-
          cd api/review-service
          mvn -B test --file pom.xml
      - name: Generate Coverage Report
        run: |
          cd api/review-service
          mvn -B package --file pom.xml

      - name: Upload Report
        uses: 'actions/upload-artifact@v2'
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/api/review-service/target/site/jacoco/jacoco.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/api/review-service/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Review Microservice Code Coverage

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: review
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: somepassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
